spring.application.name: fixit
spring:
  datasource:
    url: jdbc:postgresql://ep-little-hall-a98gcstv-pooler.gwc.azure.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_2dXAlUiSZp5a
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
